[2018-05-15 11:14:10 +0800] [37712] [INFO] Starting gunicorn 19.8.1
[2018-05-15 11:14:10 +0800] [37712] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2018-05-15 11:14:10 +0800] [37712] [ERROR] Retrying in 1 second.
[2018-05-15 11:14:11 +0800] [37712] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2018-05-15 11:14:11 +0800] [37712] [ERROR] Retrying in 1 second.
[2018-05-15 11:14:12 +0800] [37712] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2018-05-15 11:14:12 +0800] [37712] [ERROR] Retrying in 1 second.
[2018-05-15 11:14:13 +0800] [37712] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2018-05-15 11:14:13 +0800] [37712] [ERROR] Retrying in 1 second.
[2018-05-15 11:14:14 +0800] [37712] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2018-05-15 11:14:14 +0800] [37712] [ERROR] Retrying in 1 second.
[2018-05-15 11:14:15 +0800] [37712] [ERROR] Can't connect to ('0.0.0.0', 5000)
[2018-05-15 12:10:27 +0800] [41659] [INFO] Starting gunicorn 19.8.1
[2018-05-15 12:10:27 +0800] [41659] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2018-05-15 12:10:27 +0800] [41659] [ERROR] Retrying in 1 second.
[2018-05-15 12:10:28 +0800] [41659] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2018-05-15 12:10:28 +0800] [41659] [ERROR] Retrying in 1 second.
[2018-05-15 12:10:29 +0800] [41659] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2018-05-15 12:10:29 +0800] [41659] [ERROR] Retrying in 1 second.
[2018-05-15 12:10:30 +0800] [41659] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2018-05-15 12:10:30 +0800] [41659] [ERROR] Retrying in 1 second.
[2018-05-15 12:10:31 +0800] [41659] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2018-05-15 12:10:31 +0800] [41659] [ERROR] Retrying in 1 second.
[2018-05-15 12:10:32 +0800] [41659] [ERROR] Can't connect to ('0.0.0.0', 5000)
[2018-05-15 12:14:34 +0800] [41952] [INFO] Starting gunicorn 19.8.1
[2018-05-15 12:14:34 +0800] [41952] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2018-05-15 12:14:34 +0800] [41952] [ERROR] Retrying in 1 second.
[2018-05-15 12:14:35 +0800] [41952] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2018-05-15 12:14:35 +0800] [41952] [ERROR] Retrying in 1 second.
[2018-05-15 12:14:36 +0800] [41952] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2018-05-15 12:14:36 +0800] [41952] [ERROR] Retrying in 1 second.
[2018-05-15 12:14:37 +0800] [41952] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2018-05-15 12:14:37 +0800] [41952] [ERROR] Retrying in 1 second.
[2018-05-15 12:14:38 +0800] [41952] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2018-05-15 12:14:38 +0800] [41952] [ERROR] Retrying in 1 second.
[2018-05-15 12:14:39 +0800] [41952] [ERROR] Can't connect to ('0.0.0.0', 5000)
[2018-05-15 12:15:12 +0800] [41994] [INFO] Starting gunicorn 19.8.1
[2018-05-15 12:15:12 +0800] [41994] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2018-05-15 12:15:12 +0800] [41994] [ERROR] Retrying in 1 second.
[2018-05-15 12:15:13 +0800] [41994] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2018-05-15 12:15:13 +0800] [41994] [ERROR] Retrying in 1 second.
[2018-05-15 12:15:14 +0800] [41994] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2018-05-15 12:15:14 +0800] [41994] [ERROR] Retrying in 1 second.
[2018-05-15 12:15:19 +0800] [41998] [INFO] Starting gunicorn 19.8.1
[2018-05-15 12:15:19 +0800] [41998] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2018-05-15 12:15:19 +0800] [41998] [ERROR] Retrying in 1 second.
[2018-05-15 12:15:20 +0800] [41998] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2018-05-15 12:15:20 +0800] [41998] [ERROR] Retrying in 1 second.
[2018-05-15 12:15:21 +0800] [41998] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2018-05-15 12:15:21 +0800] [41998] [ERROR] Retrying in 1 second.
[2018-05-15 12:15:22 +0800] [41998] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2018-05-15 12:15:22 +0800] [41998] [ERROR] Retrying in 1 second.
[2018-05-15 12:15:23 +0800] [41998] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2018-05-15 12:15:23 +0800] [41998] [ERROR] Retrying in 1 second.
[2018-05-15 12:15:24 +0800] [41998] [ERROR] Can't connect to ('0.0.0.0', 5000)
[2018-05-15 12:17:18 +0800] [42123] [INFO] Starting gunicorn 19.8.1
[2018-05-15 12:17:18 +0800] [42123] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2018-05-15 12:17:18 +0800] [42123] [ERROR] Retrying in 1 second.
[2018-05-15 12:17:19 +0800] [42123] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2018-05-15 12:17:19 +0800] [42123] [ERROR] Retrying in 1 second.
[2018-05-15 12:17:20 +0800] [42123] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2018-05-15 12:17:20 +0800] [42123] [ERROR] Retrying in 1 second.
[2018-05-15 12:17:21 +0800] [42123] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2018-05-15 12:17:21 +0800] [42123] [ERROR] Retrying in 1 second.
[2018-05-15 12:17:22 +0800] [42123] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2018-05-15 12:17:22 +0800] [42123] [ERROR] Retrying in 1 second.
[2018-05-15 12:17:23 +0800] [42123] [ERROR] Can't connect to ('0.0.0.0', 5000)
[2018-05-15 12:19:34 +0800] [42264] [INFO] Starting gunicorn 19.8.1
[2018-05-15 12:19:34 +0800] [42264] [INFO] Listening at: http://0.0.0.0:5000 (42264)
[2018-05-15 12:19:34 +0800] [42264] [INFO] Using worker: sync
[2018-05-15 12:19:34 +0800] [42267] [INFO] Booting worker with pid: 42267
[2018-05-15 12:19:34 +0800] [42270] [INFO] Booting worker with pid: 42270
[2018-05-15 12:19:34 +0800] [42271] [INFO] Booting worker with pid: 42271
[2018-05-15 12:19:34 +0800] [42272] [INFO] Booting worker with pid: 42272
[2018-05-15 17:20:09 +0800] [55258] [INFO] Starting gunicorn 19.8.1
[2018-05-15 17:20:09 +0800] [55258] [INFO] Listening at: http://0.0.0.0:5000 (55258)
[2018-05-15 17:20:09 +0800] [55258] [INFO] Using worker: sync
[2018-05-15 17:20:09 +0800] [55261] [INFO] Booting worker with pid: 55261
[2018-05-15 17:20:09 +0800] [55264] [INFO] Booting worker with pid: 55264
[2018-05-15 17:20:09 +0800] [55265] [INFO] Booting worker with pid: 55265
[2018-05-15 17:20:09 +0800] [55266] [INFO] Booting worker with pid: 55266
[2018-05-15 17:22:58 +0800] [55393] [INFO] Starting gunicorn 19.8.1
[2018-05-15 17:22:58 +0800] [55393] [INFO] Listening at: http://0.0.0.0:5000 (55393)
[2018-05-15 17:22:58 +0800] [55393] [INFO] Using worker: sync
[2018-05-15 17:22:58 +0800] [55396] [INFO] Booting worker with pid: 55396
[2018-05-15 17:22:58 +0800] [55399] [INFO] Booting worker with pid: 55399
[2018-05-15 17:22:58 +0800] [55400] [INFO] Booting worker with pid: 55400
[2018-05-15 17:22:58 +0800] [55401] [INFO] Booting worker with pid: 55401
[2018-05-15 17:29:15 +0800] [55393] [CRITICAL] WORKER TIMEOUT (pid:55400)
[2018-05-15 17:29:15 +0800] [55393] [CRITICAL] WORKER TIMEOUT (pid:55401)
[2018-05-15 17:29:15 +0800] [55393] [CRITICAL] WORKER TIMEOUT (pid:55399)
[2018-05-15 17:29:15 +0800] [55400] [INFO] Worker exiting (pid: 55400)
[2018-05-15 17:29:15 +0800] [55401] [INFO] Worker exiting (pid: 55401)
[2018-05-15 17:29:15 +0800] [55399] [INFO] Worker exiting (pid: 55399)
[2018-05-15 17:29:15 +0800] [55665] [INFO] Booting worker with pid: 55665
[2018-05-15 17:29:15 +0800] [55666] [INFO] Booting worker with pid: 55666
[2018-05-15 17:29:15 +0800] [55667] [INFO] Booting worker with pid: 55667
[2018-05-15 17:31:17 +0800] [55781] [INFO] Starting gunicorn 19.8.1
[2018-05-15 17:31:17 +0800] [55781] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2018-05-15 17:31:17 +0800] [55781] [ERROR] Retrying in 1 second.
[2018-05-15 17:31:18 +0800] [55781] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2018-05-15 17:31:18 +0800] [55781] [ERROR] Retrying in 1 second.
[2018-05-15 17:31:19 +0800] [55781] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2018-05-15 17:31:19 +0800] [55781] [ERROR] Retrying in 1 second.
[2018-05-15 17:31:20 +0800] [55781] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2018-05-15 17:31:20 +0800] [55781] [ERROR] Retrying in 1 second.
[2018-05-15 17:31:21 +0800] [55781] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2018-05-15 17:31:21 +0800] [55781] [ERROR] Retrying in 1 second.
[2018-05-15 17:31:22 +0800] [55781] [ERROR] Can't connect to ('0.0.0.0', 5000)
[2018-05-15 17:31:53 +0800] [55814] [INFO] Starting gunicorn 19.8.1
[2018-05-15 17:31:53 +0800] [55814] [INFO] Listening at: http://0.0.0.0:5000 (55814)
[2018-05-15 17:31:53 +0800] [55814] [INFO] Using worker: sync
[2018-05-15 17:31:53 +0800] [55817] [INFO] Booting worker with pid: 55817
[2018-05-15 17:31:53 +0800] [55820] [INFO] Booting worker with pid: 55820
[2018-05-15 17:31:53 +0800] [55821] [INFO] Booting worker with pid: 55821
[2018-05-15 17:31:54 +0800] [55822] [INFO] Booting worker with pid: 55822
[2018-05-15 17:51:19 +0800] [56709] [INFO] Starting gunicorn 19.8.1
[2018-05-15 17:51:19 +0800] [56709] [INFO] Listening at: http://0.0.0.0:5000 (56709)
[2018-05-15 17:51:19 +0800] [56709] [INFO] Using worker: sync
[2018-05-15 17:51:19 +0800] [56713] [INFO] Booting worker with pid: 56713
[2018-05-15 17:51:19 +0800] [56715] [INFO] Booting worker with pid: 56715
[2018-05-15 17:51:19 +0800] [56717] [INFO] Booting worker with pid: 56717
[2018-05-15 17:51:19 +0800] [56718] [INFO] Booting worker with pid: 56718
[2018-05-18 11:40:40 +0800] [56709] [CRITICAL] WORKER TIMEOUT (pid:56717)
[2018-05-18 11:40:40 +0800] [56717] [INFO] Worker exiting (pid: 56717)
[2018-05-18 11:40:40 +0800] [17391] [INFO] Booting worker with pid: 17391
[2018-05-21 15:02:06 +0800] [97866] [INFO] Starting gunicorn 19.8.1
[2018-05-21 15:02:06 +0800] [97866] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2018-05-21 15:02:06 +0800] [97866] [ERROR] Retrying in 1 second.
[2018-05-21 15:02:07 +0800] [97866] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2018-05-21 15:02:07 +0800] [97866] [ERROR] Retrying in 1 second.
[2018-05-21 15:02:09 +0800] [97869] [INFO] Starting gunicorn 19.8.1
[2018-05-21 15:02:09 +0800] [97869] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2018-05-21 15:02:09 +0800] [97869] [ERROR] Retrying in 1 second.
[2018-05-21 15:02:10 +0800] [97869] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2018-05-21 15:02:10 +0800] [97869] [ERROR] Retrying in 1 second.
[2018-05-21 15:02:11 +0800] [97869] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2018-05-21 15:02:11 +0800] [97869] [ERROR] Retrying in 1 second.
[2018-05-21 15:02:12 +0800] [97869] [INFO] Listening at: http://0.0.0.0:5000 (97869)
[2018-05-21 15:02:12 +0800] [97869] [INFO] Using worker: sync
[2018-05-21 15:02:12 +0800] [97878] [INFO] Booting worker with pid: 97878
[2018-05-21 15:02:12 +0800] [97880] [INFO] Booting worker with pid: 97880
[2018-05-21 15:02:12 +0800] [97881] [INFO] Booting worker with pid: 97881
[2018-05-21 15:02:12 +0800] [97882] [INFO] Booting worker with pid: 97882
[2018-05-21 15:02:20,343] ERROR in app: Exception on /user/content [POST]
Traceback (most recent call last):
  File "/Users/dady/pp/login/venv/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dady/pp/login/venv/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dady/pp/login/venv/lib/python2.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/dady/pp/login/venv/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/dady/pp/login/venv/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dady/pp/login/venv/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/dady/pp/login/myapp.py", line 50, in content
    if password == select_.email:
NameError: global name 'password' is not defined
[2018-05-21 15:59:06 +0800] [1012] [INFO] Starting gunicorn 19.8.1
[2018-05-21 15:59:06 +0800] [1012] [INFO] Listening at: http://0.0.0.0:5000 (1012)
[2018-05-21 15:59:06 +0800] [1012] [INFO] Using worker: sync
[2018-05-21 15:59:06 +0800] [1015] [INFO] Booting worker with pid: 1015
[2018-05-21 15:59:06 +0800] [1018] [INFO] Booting worker with pid: 1018
[2018-05-21 15:59:06 +0800] [1019] [INFO] Booting worker with pid: 1019
[2018-05-21 15:59:06 +0800] [1020] [INFO] Booting worker with pid: 1020
[2018-05-21 15:59:29,045] ERROR in app: Exception on /user/content [POST]
Traceback (most recent call last):
  File "/Users/dady/pp/login/venv/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dady/pp/login/venv/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dady/pp/login/venv/lib/python2.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/dady/pp/login/venv/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/dady/pp/login/venv/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dady/pp/login/venv/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/dady/pp/login/myapp.py", line 50, in content
    if password == select_.email:
NameError: global name 'password' is not defined
[2018-05-21 16:04:14 +0800] [1012] [INFO] Handling signal: term
[2018-05-21 16:04:14 +0800] [1018] [INFO] Worker exiting (pid: 1018)
[2018-05-21 16:04:14 +0800] [1019] [INFO] Worker exiting (pid: 1019)
[2018-05-21 16:04:14 +0800] [1020] [INFO] Worker exiting (pid: 1020)
[2018-05-21 16:04:14 +0800] [1015] [INFO] Worker exiting (pid: 1015)
[2018-05-21 16:04:17 +0800] [1379] [INFO] Starting gunicorn 19.8.1
[2018-05-21 16:04:17 +0800] [1379] [INFO] Listening at: http://0.0.0.0:5000 (1379)
[2018-05-21 16:04:17 +0800] [1379] [INFO] Using worker: sync
[2018-05-21 16:04:17 +0800] [1382] [INFO] Booting worker with pid: 1382
[2018-05-21 16:04:17 +0800] [1385] [INFO] Booting worker with pid: 1385
[2018-05-21 16:04:17 +0800] [1386] [INFO] Booting worker with pid: 1386
[2018-05-21 16:04:17 +0800] [1387] [INFO] Booting worker with pid: 1387
[2018-05-21 16:04:21 +0800] [1393] [INFO] Starting gunicorn 19.8.1
[2018-05-21 16:04:21 +0800] [1393] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2018-05-21 16:04:21 +0800] [1393] [ERROR] Retrying in 1 second.
[2018-05-21 16:04:22 +0800] [1393] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2018-05-21 16:04:22 +0800] [1393] [ERROR] Retrying in 1 second.
[2018-05-21 16:04:23 +0800] [1393] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2018-05-21 16:04:23 +0800] [1393] [ERROR] Retrying in 1 second.
[2018-05-21 16:04:24 +0800] [1393] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2018-05-21 16:04:24 +0800] [1393] [ERROR] Retrying in 1 second.
[2018-05-21 16:04:25 +0800] [1393] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2018-05-21 16:04:25 +0800] [1393] [ERROR] Retrying in 1 second.
[2018-05-21 16:04:26 +0800] [1393] [ERROR] Can't connect to ('0.0.0.0', 5000)
[2018-05-21 16:18:06 +0800] [2083] [INFO] Starting gunicorn 19.8.1
[2018-05-21 16:18:06 +0800] [2083] [INFO] Listening at: http://0.0.0.0:5000 (2083)
[2018-05-21 16:18:06 +0800] [2083] [INFO] Using worker: sync
[2018-05-21 16:18:06 +0800] [2086] [INFO] Booting worker with pid: 2086
[2018-05-21 16:18:06 +0800] [2089] [INFO] Booting worker with pid: 2089
[2018-05-21 16:18:06 +0800] [2090] [INFO] Booting worker with pid: 2090
[2018-05-21 16:18:06 +0800] [2091] [INFO] Booting worker with pid: 2091
[2018-05-21 16:18:09 +0800] [2092] [INFO] Starting gunicorn 19.8.1
[2018-05-21 16:18:09 +0800] [2092] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2018-05-21 16:18:09 +0800] [2092] [ERROR] Retrying in 1 second.
[2018-05-21 16:18:10 +0800] [2092] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2018-05-21 16:18:10 +0800] [2092] [ERROR] Retrying in 1 second.
[2018-05-21 16:18:11 +0800] [2092] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2018-05-21 16:18:11 +0800] [2092] [ERROR] Retrying in 1 second.
[2018-05-21 16:18:12 +0800] [2092] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2018-05-21 16:18:12 +0800] [2092] [ERROR] Retrying in 1 second.
[2018-05-21 16:18:13 +0800] [2092] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2018-05-21 16:18:13 +0800] [2092] [ERROR] Retrying in 1 second.
[2018-05-21 16:18:14 +0800] [2092] [ERROR] Can't connect to ('0.0.0.0', 5000)
[2018-05-21 16:22:31 +0800] [2314] [INFO] Starting gunicorn 19.8.1
[2018-05-21 16:22:31 +0800] [2314] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2018-05-21 16:22:31 +0800] [2314] [ERROR] Retrying in 1 second.
[2018-05-21 16:22:32 +0800] [2314] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2018-05-21 16:22:32 +0800] [2314] [ERROR] Retrying in 1 second.
[2018-05-21 16:22:33 +0800] [2314] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2018-05-21 16:22:33 +0800] [2314] [ERROR] Retrying in 1 second.
[2018-05-21 16:22:34 +0800] [2314] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2018-05-21 16:22:34 +0800] [2314] [ERROR] Retrying in 1 second.
[2018-05-21 16:22:35 +0800] [2314] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2018-05-21 16:22:35 +0800] [2314] [ERROR] Retrying in 1 second.
[2018-05-21 16:22:36 +0800] [2314] [ERROR] Can't connect to ('0.0.0.0', 5000)
[2018-05-21 16:24:16 +0800] [2403] [INFO] Starting gunicorn 19.8.1
[2018-05-21 16:24:16 +0800] [2403] [INFO] Listening at: http://0.0.0.0:5000 (2403)
[2018-05-21 16:24:16 +0800] [2403] [INFO] Using worker: sync
[2018-05-21 16:24:16 +0800] [2406] [INFO] Booting worker with pid: 2406
[2018-05-21 16:24:16 +0800] [2408] [INFO] Booting worker with pid: 2408
[2018-05-21 16:24:16 +0800] [2409] [INFO] Booting worker with pid: 2409
[2018-05-21 16:24:16 +0800] [2410] [INFO] Booting worker with pid: 2410
[2018-05-21 16:24:41,316] ERROR in app: Exception on /user/content [POST]
Traceback (most recent call last):
  File "/Users/dady/pp/login/venv/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dady/pp/login/venv/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dady/pp/login/venv/lib/python2.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/dady/pp/login/venv/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/dady/pp/login/venv/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dady/pp/login/venv/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/dady/pp/login/myapp.py", line 50, in content
    if password == select_.email:
NameError: global name 'password' is not defined
